<?
$PERM["/"]["9"]="D";
$PERM["/"]["*"]="D";
$PERM["bitrix"]["9"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["2"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["3"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["4"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["8"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["6"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["7"]="W";
$PERM["lichnyy-kabinet-prodavtsa"]["5"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["2"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["3"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["4"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["8"]="W";
$PERM["lichnyy-kabinet-pokupatelya"]["6"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["7"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["5"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
?>