<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Контакты");
?><br>
 <?$APPLICATION->IncludeComponent(
	"bitrix:main.include",
	"",
Array()
);?><br>
 <br>
 Контакты<br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>